[project]
name = "f1-superfan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "ollama>=0.6.0",
    "opencv-python>=4.12.0.88",
    "pyyaml>=6.0.3",
    "together>=1.5.26",
]
